travis:
  secure:
    BINSTAR_TOKEN: lLZFmujK5iVvygter2QUg8+KsUbBQ4xDiXQcHLe5DcyfnOfg6qhl4J6QM3OH7QWE0PuczTTEhPDZXzI8yBOFNsDnpnDoUWrvFLXVEi7Y+9RkuN+lc1DoRoiy3pW9Mi/BD5mdXC5vjWW+TFW33rlXzZGCwCb33op43emnRlP9Lxe2x2kuq98fApeYJVJCMAMPGbA2/8fe9Ao5Vd80qkVAwB20KQfp1wTH4uB4VZtTsUhL/w9itZ6MTnssRACxI17e9IT1Zyvilj2WhJgzcH4jbXnBXPbIYC8gAyegZR5m0GvOpsqg6IAUb9WjgLXmi3QeH6qHFLVLZK2+KIS3XiHCb3qeaLoYLYe7H8CZVz+dETNm7r4iu79lwXrhFyBrHCN420gR6bHkJhRFOZkphyjsTRlbBwz+sdPtW96I2mj8K7V5i//LlCECAimfCUWwnofgRx/eqx7OZQ3fG2skjRSrV4b/QHL4Sen+JctXbKckSHMlO+SfZ/xLrB49gsg6OmUbiFkId4jDrapkrISA2fOf8yiKR6wghJnHSbF1X4yWYudsPx01eKtRnj2yrOYOLNx6i3jqe+C0CNsLR5L/GEEUU5TSdr98++m/IqXJX0ozpXhMPbLN5Mvq1TgJSKbvYaEBc74F/xwiO10aayzygspXTD5CaZlVQhT/FPUvERHgvP0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
